<a href="https://colab.research.google.com/github/Aksingh9717/Machine-Learning-data-science/blob/main/datetime_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
time = pd.read_csv('/content/messages.csv')
date = pd.read_csv('/content/orders.csv')

In [ ]:
date.sample(5)

           date  product_id  city_id  orders
620  2019-03-21        3220       28       1
359  2019-03-23        3339       22      38
129  2018-12-06        7413       13       6
951  2018-08-02        2238       22       5
281  2019-06-17        4379        4       1

In [ ]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [ ]:
#conerting to datetime datatype
date['date']=pd.to_datetime(date['date'])

In [ ]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [ ]:
#extract year
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
444 2019-07-24        6115       22      29       2019
622 2018-09-21        3234       25       2       2018
9   2018-08-30        4373       11       3       2018
539 2019-12-08        2831       16       4       2019
820 2019-07-27        7239       22       2       2019

In [ ]:
#extract month
date['month_month_no']= date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  month_month_no
283 2018-10-17         390        9       5       2018              10
248 2019-01-04        3614       29       1       2019               1
345 2018-07-26        6857       18      61       2018               7
991 2019-01-12        5780        0       2       2019               1
216 2019-12-13        3493       26       9       2019              12

In [ ]:
#extract month name
date['date_month_name'] = date['date'].dt.month_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,month_month_no,date_month_name
663,2018-11-19,3761,16,1,2018,11,November
814,2019-06-13,6438,24,8,2019,6,June
768,2018-12-30,4990,1,2,2018,12,December
136,2019-08-01,2200,3,3,2019,8,August
703,2019-08-02,5187,22,4,2019,8,August

In [ ]:
#extract days
date['date_day'] = date['date'].dt.day
date.sample()

,date,product_id,city_id,orders,date_year,month_month_no,date_month_name,date_day
67,2018-11-18,3604,16,5,2018,11,November,18

In [ ]:
#day of week
date['dayofweek'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,month_month_no,date_month_name,date_day,dayofweek
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [ ]:
#dayofweek- name
date['date_dayofweek'] = date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,month_month_no,date_month_name,date_day,dayofweek,date_dayofweek
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [ ]:
#is weekend???
date['date_is_weekend']=np.where(date['date_dayofweek'].isin(['Sunday','Saturday']),1,0)
date.head()

,date,product_id,city_id,orders,date_year,month_month_no,date_month_name,date_day,dayofweek,date_dayofweek,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

In [ ]:
#extract week of the year

date['date_week'] = date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,date_year,month_month_no,date_month_name,date_day,dayofweek,date_dayofweek,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

In [ ]:
#extract quarter
date['date']=date['date'].dt.quarter
date.sample(5)

,date,product_id,city_id,orders,date_year,month_month_no,date_month_name,date_day,dayofweek,date_dayofweek,date_is_weekend,date_week
136,3,2200,3,3,2019,8,August,1,3,Thursday,0,31
810,2,1187,2,45,2019,6,June,25,1,Tuesday,0,26
438,4,1985,14,45,2018,12,December,31,0,Monday,0,1
487,2,6095,9,1,2019,4,April,18,3,Thursday,0,16
865,4,803,23,3,2018,10,October,13,5,Saturday,1,41

In [ ]:
#extract time elapsed bewteen dates

import datetime

today = datetime.datetime.today()
today

datetime.datetime(2026, 3, 29, 10, 13, 16, 648592)

In [ ]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [ ]:
#converting to datettime datatype

time['date'] = pd.to_datetime(time['date'])

In [ ]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [ ]:
time['hour']=time['date'].dt.hour
time['minute']=time['date'].dt.minute
time['sec']=time['date'].dt.second

In [ ]:
time.head()

,date,msg,hour,minute,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [ ]:
#extract time part

time['time']= time['date'].dt.time
time.head()

,date,msg,hour,minute,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [ ]:
#time difference
today - time['date']

0     4487 days 09:23:16.648592
1     4351 days 10:33:16.648592
2     4837 days 09:52:16.648592
3     4139 days 09:42:16.648592
4     4536 days 11:02:16.648592
                 ...
995   5126 days 09:23:16.648592
996   4447 days 10:59:16.648592
997   4912 days 10:36:16.648592
998   5028 days 10:39:16.648592
999   4300 days 10:48:16.648592
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
#in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.877106e+08
1      3.759644e+08
2      4.179523e+08
3      3.576445e+08
4      3.919501e+08
           ...
995    4.429202e+08
996    3.842604e+08
997    4.244350e+08
998    4.344576e+08
999    3.715589e+08
Name: date, Length: 1000, dtype: float64

In [ ]:
#in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.461843e+06
1      6.266073e+06
2      6.965872e+06
3      5.960742e+06
4      6.532502e+06
           ...
995    7.382003e+06
996    6.404339e+06
997    7.073916e+06
998    7.240959e+06
999    6.192648e+06
Name: date, Length: 1000, dtype: float64

In [ ]:
#in hours

(today - time['date'])/np.timedelta64(1,'s')

0      3.877106e+08
1      3.759644e+08
2      4.179523e+08
3      3.576445e+08
4      3.919501e+08
           ...
995    4.429202e+08
996    3.842604e+08
997    4.244350e+08
998    4.344576e+08
999    3.715589e+08
Name: date, Length: 1000, dtype: float64